Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Orchard.ContentManagement;
using Orchard.DisplayManagement;
using Orchard.Localization;
using Orchard.Mvc;
using Orchard.Security;
using Orchard.Themes;
using Skywalker.Webshop.Extensibility;
using Skywalker.Webshop.Models;
using Skywalker.Webshop.Services;
using Orchard;



namespace Skywalker.Webshop.Controllers {
    public class OrderController : Controller {
        private readonly dynamic _shapeFactory;
        private readonly IOrderService _orderService;
        private readonly IAuthenticationService _authenticationService;
        private readonly IShoppingCart _shoppingCart;
        private readonly ICustomerService _customerService;
        private readonly IEnumerable<IPaymentServiceProvider> _paymentServiceProviders;
        private readonly Localizer _t;

        private readonly IOrchardServices _services;

        public OrderController(
            IOrchardServices services,
            IShapeFactory shapeFactory, 
            IOrderService orderService, 
            IAuthenticationService authenticationService, 
            IShoppingCart shoppingCart, 
            ICustomerService customerService,
            IEnumerable<IPaymentServiceProvider> paymentServiceProviders
            ) {
                _services = services;
            _shapeFactory                  = shapeFactory;
            _orderService                  = orderService;
            _authenticationService         = authenticationService;
            _shoppingCart                  = shoppingCart;
            _customerService               = customerService;
            _paymentServiceProviders       = paymentServiceProviders;
            _t                             = NullLocalizer.Instance;
        }

        [Themed, HttpPost]
        public ActionResult Create() {

            var user = _authenticationService.GetAuthenticatedUser();

            if(user == null)
                return new HttpUnauthorizedResult();
               // throw new OrchardSecurityException(_t("Login required"));

            var customer = user.ContentItem.As<CustomerPart>();

            if(customer == null)
                throw new InvalidOperationException("The current user is not a customer");

            var order = _orderService.CreateOrder(customer.Id, _shoppingCart.Items);

            // Give payment service providers a chance to process payment by sending a event. If no PSP handled the event, we'll just continue by displaying the created order.
            // Raise an OrderCreated event
            // Fire the PaymentRequest event
            var paymentRequest = new PaymentRequest(order);

            foreach (var handler in _paymentServiceProviders) {
                handler.RequestPayment(paymentRequest);
                // If the handler responded, it will set the action result
                if (paymentRequest.WillHandlePayment) {
                    return paymentRequest.ActionResult;
                }
            }
//////////////////////////////////////////////////////////////////////
            // If we got here, no PSP handled the PaymentRequest event, so we'll just display the order.
            var shape = _shapeFactory.Order_Created(
                Order: order,
                Products: _orderService.GetProducts(order.Details).ToArray(),
                Customer: customer,
                ContentManager: _services.ContentManager,
                InvoiceAddress: (dynamic)_customerService.GetAddress(user.Id, "InvoiceAddress"),
                ShippingAddress: (dynamic)_customerService.GetAddress(user.Id, "ShippingAddress")
            );
            return new ShapeResult(this, shape);
        }

        [Themed]
        public ActionResult PaymentResponse() {

            var args = new PaymentResponse(HttpContext);

            foreach (var handler in _paymentServiceProviders) {
                handler.ProcessResponse(args);

                if (args.WillHandleResponse)
                    break;
            }

            if(!args.WillHandleResponse)
                throw new OrchardException(_t("Such things mean trouble"));

            var order = _orderService.GetOrderByNumber(args.OrderReference);
            _orderService.UpdateOrderStatus(order, args);

            if (order.Status == OrderStatus.Paid) {
                // Send some notification mail message to the customer that the order was paid.
                // We may also initiate the shipping process from here
            }

            return new ShapeResult(this, _shapeFactory.Order_PaymentResponse(Order: order, PaymentResponse: args));
        }
    }
}

Controllers/ShoppingCartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Orchard;
using Orchard.Mvc;
using Orchard.Themes;
using Skywalker.Webshop.Models;
using Skywalker.Webshop.Services;
using Skywalker.Webshop.ViewModels;

namespace Skywalker.Webshop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCart _shoppingCart;
        private readonly IOrchardServices _services;

        public ShoppingCartController(IShoppingCart shoppingCart, IOrchardServices services)
        {
            _shoppingCart = shoppingCart;
            _services = services;
        }

        [HttpPost]
        public ActionResult Add(int id) {
            
            // Add the specified content id to the shopping cart with a quantity of 1.
            _shoppingCart.Add(id, 1); 

            // Redirect the user to the Index action (yet to be created)
            return RedirectToAction("Index");
        }

        [Themed]
        public ActionResult Index() {

            // Create a new shape using the "New" property of IOrchardServices.
            var shape = _services.New.ShoppingCart(
                Products: _shoppingCart.GetProducts().Select(p => _services.New.ShoppingCartItem(
                    ProductPart: p.ProductPart, 
                    Quantity: p.Quantity,
                    Title: _services.ContentManager.GetItemMetadata(p.ProductPart).DisplayText)
                ).ToList(),
                Total: _shoppingCart.Total(),
                Subtotal: _shoppingCart.Subtotal(),
                Vat: _shoppingCart.Vat()
            );

            // Return a ShapeResult
            return new ShapeResult(this, shape);
        }

        [HttpPost]
        public ActionResult Update(string command, UpdateShoppingCartItemViewModel[] items)
        {
            UpdateShoppingCart(items);

            if (Request.IsAjaxRequest())
                return Json(true);

            switch (command)
            {
                case "Checkout":
                    return RedirectToAction("SignupOrLogin", "Checkout");
                case "ContinueShopping":
                    break;
                case "Update":
                    break;
            }
            return RedirectToAction("Index");
        }

        public ActionResult GetItems() {
            var products = _shoppingCart.GetProducts();
            
            var json = new {
                items = (from item in products
                         select new {
                             id = item.ProductPart.Id,
                             title = _services.ContentManager.GetItemMetadata(item.ProductPart).DisplayText ?? "(No TitlePart attached)",
                             unitPrice = item.ProductPart.UnitPrice,
                             quantity = item.Quantity
                         }).ToArray()
            };

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        private void UpdateShoppingCart(IEnumerable<UpdateShoppingCartItemViewModel> items) {
            
            _shoppingCart.Clear();

            if (items == null)
                return;

            _shoppingCart.AddRange(items
                .Where(item => !item.IsRemoved)
                .Select(item => new ShoppingCartItem(item.ProductId, item.Quantity < 0 ? 0 : item.Quantity))
            );

            _shoppingCart.UpdateItems();
        }
    }
}

Views/Checkout.Login.cshtml
@using Skywalker.Webshop.ViewModels
@{
    var login = (LoginViewModel)Model.Login;

    Style.Require("Skywalker.Webshop.Common");
}
 
<h2>@T("Returning customer")</h2>
<p>@T("Please login using the form below")</p>
 
@Html.ValidationSummary()
 
@using (Html.BeginFormAntiForgeryPost(Url.Action("Login", "Checkout", new { area = "Skywalker.Webshop" }))) {
    
    <article class="form">
            
        <fieldset>
            <ul>
                <li>
                    <div class="field-label">@Html.LabelFor(m => login.Email, T("Email"))</div>
                    <div class="field-editor">@Html.EditorFor(m => login.Email)</div>
                </li>
                <li>
                    <div class="field-label">@Html.LabelFor(m => login.Password, T("Password"))</div>
                    <div class="field-editor">@Html.EditorFor(m => login.Password)</div>
                </li>
            </ul>
        </fieldset>
    
        <fieldset>
            <ul>
                <li>
                    <div class="checkbox-and-label">
                        <div class="checkbox">@Html.CheckBoxFor(m => login.CreatePersistentCookie)</div>
                        <div class="label">@Html.LabelFor(m => login.CreatePersistentCookie, T("Remember me next time"))</div>
                    </div>
                </li>
            </ul>
        </fieldset>
    
        <footer class="commands">
            <ul>
                <li class="align left"><a href="#">@T("Cancel")</a></li>
                <li class="align right"><button type="submit">@T("Next")</button></li>
            </ul>
        </footer>
    
    </article>
}

Views/Checkout.SelectAddress.cshtml
@using Skywalker.Webshop.ViewModels
@{
    var addresses = (AddressesViewModel) Model.Addresses;

    Style.Require("Skywalker.Webshop.Common");
}
<h2>Address Details</h2>
<p>@T("Please provide us with your billing address and shipping address. If both addresses are the same, then you only need to provide us with your invoice address.")</p>
 
@using (Html.BeginFormAntiForgeryPost(Url.Action("SelectAddress", "Checkout", new { area = "Skywalker.Webshop" }))) {
    <article class="form">
    
        @Html.EditorFor(m => addresses.InvoiceAddress)
        @Html.EditorFor(m => addresses.ShippingAddress)
    
        <footer class="commands">
            <ul>
                <li class="align left"><a href="#">@T("Cancel")</a></li>
                <li class="align right"><button type="submit">@T("Next")</button></li>
            </ul>
        </footer>
    </article>
}

Views/Checkout.Signup.cshtml
@using Skywalker.Webshop.ViewModels
@{
    var signup = (SignupViewModel)Model.Signup;

    Style.Require("Skywalker.Webshop.Common");
}
 
<h2>@T("New customer")</h2>
<p>@T("Please fill out the form below")</p>
 
@Html.ValidationSummary()
 
@using (Html.BeginFormAntiForgeryPost(Url.Action("Signup", "Checkout", new { area = "Skywalker.Webshop" }))) {    
    <article class="form">
        <fieldset>
            <ul>
                <li>
                    <div class="field-label">@Html.LabelFor(m => signup.Title, T("Title"))</div>
                    <div class="field-editor">@Html.EditorFor(m => signup.Title)</div>
                </li>
                <li>
                    <div class="field-label">@Html.LabelFor(m => signup.FirstName, T("First name"))</div>
                    <div class="field-editor">@Html.EditorFor(m => signup.FirstName)</div>
                </li>
                <li>
                    <div class="field-label">@Html.LabelFor(m => signup.LastName, T("Last name"))</div>
                    <div class="field-editor">@Html.EditorFor(m => signup.LastName)</div>
                </li>
            </ul>
        </fieldset>
    
        <fieldset>
            <ul>
                <li>
                    <div class="field-label">@Html.LabelFor(m => signup.Email, T("Email"))</div>
                    <div class="field-editor">@Html.EditorFor(m => signup.Email)</div>
                </li>
                <li>
                    <div class="field-label">@Html.LabelFor(m => signup.Password, T("Password"))</div>
                    <div class="field-editor">@Html.EditorFor(m => signup.Password)</div>
                </li>
                <li>
                    <div class="field-label">@Html.LabelFor(m => signup.RepeatPassword, T("Repeat password"))</div>
                    <div class="field-editor">@Html.EditorFor(m => signup.RepeatPassword)</div>
                </li>
            </ul>
        </fieldset>
    
        <fieldset>
            <ul>
                <li>
                    <div class="checkbox-and-label">
                        <div class="checkbox">@Html.CheckBoxFor(m => signup.ReceiveNewsletter)</div>
                        <div class="label">@Html.LabelFor(m => signup.ReceiveNewsletter, T("Subscribe to our mailing list"))</div>
                    </div>
                </li>
                <li>
                    <div class="checkbox-and-label">
                        <div class="checkbox">@Html.CheckBoxFor(m => signup.AcceptTerms)</div>
                        <div class="label">
                            <label for="@Html.FieldIdFor(m => signup.AcceptTerms)">
                                @Html.Raw(T("I have read and accept the <a href=\"{0}\" target=\"_blank\">Terms and Conditions</a>", "#").ToString())
                            </label>
                        </div>
                    </div>
                </li>
            </ul>
        </fieldset>
    
        <footer class="commands">
            <ul>
                <li class="align left"><a href="#">@T("Cancel")</a></li>
                <li class="align right"><button type="submit">@T("Next")</button></li>
            </ul>
        </footer>
    </article>
}

Views/Checkout.SignupOrLogin.cshtml
@{
    Style.Require("Skywalker.Webshop.Common");
}
<article>
    <p>@T("Are you a returning customer or a new customer?")</p>
    
    <ul class="action bullets">
        <li><a href="@Url.Action("Login", "Checkout", new { area = "Skywalker.Webshop" })">I am a <strong>returning customer</strong> and already have an account</a></li>
        <li><a href="@Url.Action("Signup", "Checkout", new { area = "Skywalker.Webshop" })">I am a <strong>new customer</strong></a></li>
    </ul>
</article>

Views/Checkout.Summary.cshtml
@using Orchard.ContentManagement
@using Skywalker.Webshop.Models
@{
    Style.Require("Skywalker.Webshop.Checkout.Summary");
    var shoppingCart = Model.ShoppingCart;
    var invoiceAddress = Model.InvoiceAddress;
    var shippingAddress = Model.ShippingAddress;
    var items = (IList<dynamic>)shoppingCart.ShopItems;
    var subtotal = (decimal)shoppingCart.Subtotal;
    var vat = (decimal)shoppingCart.Vat;
    var total = (decimal)shoppingCart.Total;
}
@if (!items.Any())
{
    <p>You don't have any items in your shopping cart.</p>
    <a class="button" href="#">Continue shopping</a>
}
else { 
    
    <article class="shoppingcart" >
        <h2>Review your order</h2>
        <p>Please review the information below. Hit the Place Order button to proceed.</p>
        <table>
            <thead>
                <tr>
                    <td>Article</td>
                    <td class="numeric">Unit Price</td>
                    <td class="numeric">Quantity</td>
                    <td class="numeric">Total Price</td>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < items.Count; i++) {
                    var item = items[i];
                    var product = (ProductPart) item.Product;
                    var contentItem = (ContentItem) item.ContentItem;
                    var title = item.Title;
                    var quantity = (int) item.Quantity;
                    var unitPrice = product.UnitPrice;
                    var totalPrice = quantity*unitPrice;
                    <tr>
                        <td>@title</td>
                        <td class="numeric">@unitPrice.ToString("c")</td>
                        <td class="numeric">@quantity</td>
                        <td class="numeric">@totalPrice.ToString("c")</td>
                    </tr>
                }
            
            </tbody>
            <tfoot>
                <tr class="separator"><td colspan="4">&nbsp;</td></tr>
                <tr>
                    <td class="numeric label" colspan="2">Subtotal:</td>
                    <td class="numeric">@subtotal.ToString("c")</td>
                    <td></td>
                </tr>
                <tr>
                    <td class="numeric label" colspan="2">VAT (19%):</td>
                    <td class="numeric">@vat.ToString("c")</td>
                    <td></td>
                </tr>
                <tr>
                    <td class="numeric label" colspan="3">Total:</td>
                    <td class="numeric">@total.ToString("c")</td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </article>
    
    <article class="addresses form">
        <div class="invoice-address">
            <h2>Invoice Address</h2>
            <ul class="address-fields">
                <li>@invoiceAddress.Name.Value</li>
                <li>@invoiceAddress.AddressLine1.Value</li>
                <li>@invoiceAddress.AddressLine2.Value</li>
                <li>@invoiceAddress.Zipcode.Value</li>
                <li>@invoiceAddress.City.Value</li>
                <li>@invoiceAddress.Country.Value</li>
            </ul>
        </div>
        <div class="shipping-address">
            <h2>Shipping Address</h2>
            <ul class="address-fields">
                <li>@shippingAddress.Name.Value</li>
                <li>@shippingAddress.AddressLine1.Value</li>
                <li>@shippingAddress.AddressLine2.Value</li>
                <li>@shippingAddress.Zipcode.Value</li>
                <li>@shippingAddress.City.Value</li>
                <li>@shippingAddress.Country.Value</li>
            </ul>
        </div>
    </article>
    
    <article>
        <div class="group">
            <div class="align left"><a href="#">Cancel</a></div>
            @*<div class="align right"><button type="submit" name="command" value="CreateOrder">Place Order</button></div>*@
             <div class="align right">
                @using (Html.BeginFormAntiForgeryPost(Url.Action("Create", "Order", new { area = "Skywalker.Webshop" })))
                {
                    <button type="submit" name="command" value="CreateOrder">Place Order</button>
                }
            </div>
        </div>
    </article>
}

Views/Order.Created.cshtml
@using System.Globalization
@using Orchard.ContentManagement
@using Skywalker.Webshop.Models

@{
    Style.Require("Webshop.Order");

    var order = (OrderRecord) Model.Order;
    var productParts = (IList<ProductPart>) Model.Products;
    var invoiceAddress = Model.InvoiceAddress;
    var shippingAddress = Model.ShippingAddress;
    
    var contentManager=Model.ContentManager;
}
<h2>@T("Order {0} has been created", order.Number)</h2>
<p>@T("Please find your order details below")</p>

<div class="order-wrapper">
    <article class="order">
        <header>
            <ul>
                <li>
                    <div class="field-label">Order Number</div>
                    <div class="field-value">@order.Number</div>
                </li>
                <li>
                    <div class="field-label">Created</div>
                    <div class="field-value">@order.CreatedAt.ToString(CultureInfo.InvariantCulture)</div>
                </li>
                <li>
                    <div class="field-label">Status</div>
                    <div class="field-value">@order.Status</div>
                </li>
            </ul>
        </header>
        <table>
            <thead>
                <tr>
                    <td>Article</td>
                    <td class="numeric">Unit Price</td>
                    <td class="numeric">Quantity</td>
                    <td class="numeric">Total Price</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var detail in order.Details) {
                    var productPart = productParts.Single(x => x.Id == detail.ProductId);
                    var productTitle = contentManager.GetItemMetadata(productPart).DisplayText;
                    //var routePart = productPart.As<RoutePart>();
                   // var productTitle = "(No RoutePart attached)";//routePart != null ? routePart.Title : "(No RoutePart attached)";
                    <tr>
                        <td>@productTitle</td>
                        <td class="numeric">@detail.UnitPrice.ToString("c")</td>
                        <td class="numeric">@detail.Quantity</td>
                        <td class="numeric">@detail.SubTotal.ToString("c")</td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr class="separator"><td colspan="4">&nbsp;</td></tr>
                <tr>
                    <td class="numeric label" colspan="2">Subtotal:</td>
                    <td class="numeric">@order.SubTotal.ToString("c")</td>
                </tr>
                <tr>
                    <td class="numeric label" colspan="2">VAT:</td>
                    <td class="numeric">@order.Vat.ToString("c")</td>
                </tr>
                <tr>
                    <td class="numeric label" colspan="2">Total:</td>
                    <td class="numeric">@order.Total.ToString("c")</td>
                </tr>
            </tfoot>
        </table>
    </article>
    
    <article class="addresses form">
        <div class="invoice-address">
            <h2>Invoice Address</h2>
            <ul class="address-fields">
                <li>@invoiceAddress.Name.Value</li>
                <li>@invoiceAddress.AddressLine1.Value</li>
                <li>@invoiceAddress.AddressLine2.Value</li>
                <li>@invoiceAddress.Zipcode.Value</li>
                <li>@invoiceAddress.City.Value</li>
                <li>@invoiceAddress.Country.Value</li>
            </ul>
        </div>
        <div class="shipping-address">
            <h2>Shipping Address</h2>
            <ul class="address-fields">
                <li>@shippingAddress.Name.Value</li>
                <li>@shippingAddress.AddressLine1.Value</li>
                <li>@shippingAddress.AddressLine2.Value</li>
                <li>@shippingAddress.Zipcode.Value</li>
                <li>@shippingAddress.City.Value</li>
                <li>@shippingAddress.Country.Value</li>
            </ul>
        </div>
    </article>
</div>

Views/Order.PaymentResponse.cshtml
@using Skywalker.Webshop.Extensibility
@using Skywalker.Webshop.Models
@{
    var order = (OrderRecord) Model.Order;
    var paymentResponse = (PaymentResponse) Model.PaymentResponse;  
}
@if (paymentResponse.Status == PaymentResponseStatus.Success)
{
    <h2>@T("Payment was succesful")</h2>
    <p>Thanks! We succesfully received payment for order @order.Number with payment ID @paymentResponse.PaymentReference</p>
    <p>Enjoy your products and come again!</p>
}
else {
    <h2>@T("Order cancelled")</h2>
    <p>Your order (@order.Number) has been cancelled</p>
}

Views/ShoppingCart.cshtml
@using Skywalker.Webshop.Models
@{
    Style.Require("Skywalker.Webshop.ShoppingCart");
    Script.Require("Skywalker.Webshop.ShoppingCart");
    var items = (IList<dynamic>)Model.Products;
    var subtotal = (decimal) Model.Subtotal;
    var vat = (decimal) Model.Vat;
    var total = (decimal) Model.Total;
}
@if (!items.Any())
{
    <p>You don't have any items in your shopping cart.</p>
    <a class="button" href="#">Continue shopping</a>
}
else { 
    <div data-bind="visible: !hasItems()">
        <p>You don't have any items in your shopping cart.</p>
        <a class="button" href="#">Continue shopping</a>
    </div>
    
    <div data-bind="visible: hasItems()">
        <article class="shoppingcart" data-load-shoppingcart-url="@Url.Action("GetItems", "ShoppingCart", new { area = "Skywalker.WebShop" })" data-update-shoppingcart-url="@Url.Action("Update", "ShoppingCart", new { area = "Skywalker.WebShop" })">
            @using(Html.BeginFormAntiForgeryPost(Url.Action("Update", "ShoppingCart", new { area = "Skywalker.Webshop" })))
            {
                <table>
                    <thead>
                        <tr>
                            <td>Article</td>
                            <td class="numeric">Unit Price</td>
                            <td class="numeric">Quantity</td>
                            <td class="numeric">Total Price</td>
                            <td class="action"></td>
                        </tr>
                    </thead>
                    <tbody data-bind='template: {name: "itemTemplate", foreach: items}'>
                        @for (var i = 0; i < items.Count; i++) {
                            var item = items[i];
                            var product = (ProductPart) item.ProductPart;
                            var title = item.Title ?? "(no routepart attached)";
                            var quantity = (int) item.Quantity;
                            var unitPrice = product.UnitPrice;
                            var totalPrice = quantity*unitPrice;
                            <tr>
                                <td>@title</td>
                                <td class="numeric">@unitPrice.ToString("c")</td>
                                <td class="numeric">
                                    <input name="@string.Format("items[{0}].ProductId", i)" type="hidden" value="@product.Id" />
                                    <input name="@string.Format("items[{0}].IsRemoved", i)" type="hidden" value="false" />
                                    <input name="@string.Format("items[{0}].Quantity", i)" type="number" value="@quantity" />
                                </td>
                                <td class="numeric">@totalPrice.ToString("c")</td>
                                <td class="action"><a class="icon delete postback" href="#"></a></td>
                            </tr>
                        }
            
                    </tbody>
                    <tfoot>
                        <tr><td colspan="5">&nbsp;</td></tr>
                        <tr class="separator">
                            <td class="update" colspan="5"><button name="command" value="Update" type="submit">Update</button></td>
                        </tr>
                        <tr>
                            <td class="numeric label" colspan="3">Subtotal:</td>
                            <td class="numeric"><span data-bind="text: Globalize.format(calculateSubtotal(), 'c')">@subtotal.ToString("c")</span></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td class="numeric label" colspan="3">VAT (19%):</td>
                            <td class="numeric"><span data-bind="text: Globalize.format(calculateVat(), 'c')">@vat.ToString("c")</span></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td class="numeric label" colspan="3">Total:</td>
                            <td class="numeric"><span data-bind="text: Globalize.format(calculateTotal(), 'c')">@total.ToString("c")</span></td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
                <footer>
                    <div class="group">
                        <div class="align left"><button type="submit" name="command" value="ContinueShopping">Continue shopping</button></div>
                        <div class="align right"><button type="submit" name="command" value="Checkout">Proceed to checkout</button></div>
                    </div>
                </footer>
            }
        </article>
        
        <script type="text/html" id="itemTemplate">
            <tr>
                <td><span data-bind="text: title"></span></td>
                <td class="numeric"><span data-bind="text: Globalize.format(unitPrice, 'c')"></span></td>
                <td class="numeric">
                    <input data-bind="attr: { name: 'items[' + index() + '].ProductId'}, value: id" type="hidden" />
                    <input data-bind="attr: { name: 'items[' + index() + '].Quantity'}, value: quantity" type="number" />
                </td>
                <td class="numeric"><span data-bind="text: Globalize.format(total(), 'c')"></span></td>
                <td><a class="icon delete" href="#"></a></td>
            </tr>
        </script>
    </div>
}