Controllers/OrderAdminController.cs
using System.Linq;
using System.Web.Mvc;
using Orchard.ContentManagement;
using Orchard.Data;
using Orchard.DisplayManagement;
using Orchard.Localization;
using Orchard.Settings;
using Orchard.UI.Admin;
using Orchard.UI.Navigation;
using Orchard.UI.Notify;
using Orchard.Users.Models;
using Skywalker.Webshop.Models;
using Skywalker.Webshop.Services;
using Skywalker.Webshop.ViewModels;

namespace Skywalker.Webshop.Controllers
{
    [Admin]
    public class OrderAdminController : Controller
    {
        private dynamic Shape { get; set; }
        private Localizer T { get; set; }
        private readonly IOrderService _orderService;
        private readonly IRepository<ProductPartRecord> _productRepository;
        private readonly INotifier _notifier;
        private readonly ISiteService _siteService;

        public OrderAdminController(INotifier notifier, IOrderService orderService, IShapeFactory shapeFactory, IRepository<ProductPartRecord> productRepository, ISiteService siteService)
        {
            Shape = shapeFactory;
            T = NullLocalizer.Instance;
            _notifier = notifier;
            _orderService = orderService;
            _productRepository = productRepository;
            _siteService = siteService;
        }

        public ActionResult Index(PagerParameters pagerParameters) {
            var pager = new Pager(_siteService.GetSiteSettings(), pagerParameters.Page, pagerParameters.PageSize);
            var ordersQuery = _orderService.GetOrders();
            var orders = ordersQuery.Skip(pager.GetStartIndex()).Take(pager.PageSize);
            var pagerShape = Shape.Pager(pager).TotalItemCount(ordersQuery.Count());
            var model = Shape.Orders(Orders: orders.ToArray(), Pager: pagerShape);
            return View((object)model);
        }

        public ActionResult Edit(int id) {
            var order = _orderService.GetOrder(id);
            var model = BuildModel(order, new EditOrderVM(order));
            return View((object)model);
        }

        [HttpPost]
        public ActionResult Edit(EditOrderVM model)
        {
            var order = _orderService.GetOrder(model.Id);

            if (!ModelState.IsValid)
                return BuildModel(order, model);

            order.Status = model.Status;

            _notifier.Add(NotifyType.Information, T("The order has been saved"));
            return RedirectToAction("ListOrders", "CustomerAdmin", new { id = order.CustomerId });
        }

        private dynamic BuildModel(OrderRecord order, EditOrderVM editModel) {
            return Shape.Order(
                Order: order,
                Details: order.Details.Join(_productRepository.Table, x => x.ProductId, x => x.Id, (record, productRecord) => 
                    Shape.Detail
                    (
                        Sku: productRecord.Sku,
                        Price: productRecord.UnitPrice,
                        Quantity: record.Quantity,
                        Total: record.Total
                    )).ToArray(),
                EditModel: editModel
            );
        }
    }
}

Views/OrderAdmin/Edit.cshtml
@using Skywalker.Webshop.Models
@using Skywalker.Webshop.ViewModels
@{
    var editModel = (EditOrderVM) Model.EditModel;
    var order = (OrderRecord) Model.Order;
    var details = (IList<dynamic>) Model.Details;
    var quantity = 0;
    
    Layout.Title = "Edit Order";
}

@using (Html.BeginFormAntiForgeryPost()) {
    @Html.Hidden("Id", editModel.Id)
    <fieldset>
        <div class="editor-label">@Html.Label("Status")</div>
        <div class="editor-field">
            <select name="Status">
                @Html.SelectOption(order.Status, OrderStatus.New, "New")
                @Html.SelectOption(order.Status, OrderStatus.Paid, "Paid")
                @Html.SelectOption(order.Status, OrderStatus.Completed, "Completed")
                @Html.SelectOption(order.Status, OrderStatus.Cancelled, "Cancelled")
            </select>
        </div>
    </fieldset>
    <button type="submit">Save</button>
}

<br/><br/>
<fieldset>
    <legend>Order Details</legend>
    <table class="items" summary="@T("This is a table of the order details of the current order")">
        <colgroup>
            <col id="Col1" />
            <col id="Col2" />
            <col id="Col3" />
            <col id="Col4" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col">@T("Sku")</th>
                <th scope="col">@T("Price")</th>
                <th scope="col">@T("Quantity")</th>
                <th scope="col">@T("Total")</th>
            </tr>
        </thead>
        @foreach (var detail in details) {
            quantity += detail.Quantity;
        <tr>
            <td>@detail.Sku</td>
            <td>@detail.Price.ToString("c")</td>
            <td>@detail.Quantity</td>
            <td>@detail.Total.ToString("c")</td>
        </tr>
        } 
        <tfoot>
            <td><strong>Totals</strong></td>
            <td></td>
            <td><strong>@quantity</strong></td>
            <td><strong>@order.Total.ToString("c")</strong></td>
        </tfoot>
    </table>
</fieldset>

Views/OrderAdmin/Index.cshtml
@using Skywalker.Webshop.Models
@{
    var orders = (IList<OrderRecord>) Model.Orders;
    Layout.Title = T("Orders");
}

<table class="items" summary="@T("This is a table of the orders of the current customer in your application")">
        <colgroup>
            <col id="Col1" />
            <col id="Col2" />
            <col id="Col3" />
            <col id="Col4" />
            <col id="Col5" />
            <col id="Col6" />
            <col id="Col7" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col">&nbsp;&darr;</th>
                <th scope="col">@T("Number")</th>
                <th scope="col">@T("Status")</th>
                <th scope="col">@T("CustomerId")</th>
                <th scope="col">@T("Total")</th>
                <th scope="col">@T("Created")</th>
                <th scope="col">@T("Paid")</th>
                <th scope="col">@T("Actions")</th>
            </tr>
        </thead>
        @foreach (var order in orders) {
        <tr>
            <td>@order.Id</td>
            <td>@order.Number</td>
            <td>@order.Status</td>
            <td><a href="@Url.Action("ListOrders", "CustomerAdmin", new { id = order.CustomerId })">@order.CustomerId</a></td>
            <td>@order.Total</td>
            <td>@order.CreatedAt</td>
            <td>@order.PaidAt</td>
            <td>
                <div>
                    <a href="@Url.Action("Edit", "OrderAdmin", new {order.Id, returnUrl = Request.Url.PathAndQuery})" title="@T("Edit")">@T("Edit")</a>
                </div>
            </td>
        </tr>
        } 
    </table>