Controllers/SimulatedPaymentServiceProviderController.cs
using System;
using System.Web.Mvc;
using Orchard.DisplayManagement;
using Orchard.Themes;

namespace Skywalker.Webshop.Controllers {
    public class SimulatedPaymentServiceProviderController : Controller {
        
        private readonly dynamic _shapeFactory;

        public SimulatedPaymentServiceProviderController(IShapeFactory shapeFactory) {
            _shapeFactory = shapeFactory;
        }

        [Themed]
        public ActionResult Index(string orderReference, int amount) {
            var model = _shapeFactory.PaymentRequest(
                OrderReference: orderReference,
                Amount: amount
                );

            return View(model);
        }

        [HttpPost]
        public ActionResult Command(string command, string orderReference) {

            // Generate a fake payment ID
            var paymentId = new Random(Guid.NewGuid().GetHashCode()).Next(1000, 9999);

            // Redirect back to the webshop
            return RedirectToAction("PaymentResponse", "Order", new {area = "Skywalker.Webshop", paymentId = paymentId, result = command, orderReference});
        }
    }
}

Views/SimulatedPaymentServiceProvider/Index.cshtml
@{
    var orderReference = (string) Model.OrderReference;
    var amount = (decimal)((int) Model.Amount) / 100;
    var commands = new[] { "Success", "Failure", "Cancelled", "Exception" };

    Style.Require("Webshop.SimulatedPSP");
}

<h2>Payment Service Provider Simulation</h2>
<p>
    Received a payment request with order reference <strong>@orderReference</strong><br/>
    Amount: <strong>@amount.ToString("c")</strong>
</p>
@using (Html.BeginFormAntiForgeryPost(Url.Action("Command", "SimulatedPaymentServiceProvider", new {area = "Skywalker.Webshop"}))) {
    <article class="form">
        <input type="hidden" name="orderReference" value="@orderReference"/>
        <ul class="commands">
            @foreach (var command in commands) {
                <li><button type="submit" name="command" value="@command">@command</button></li>
            }
        </ul>
    </article>
}