Controllers/CustomerAdminController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Orchard.ContentManagement;
using Orchard.DisplayManagement;
using Orchard.Localization;
using Orchard.Settings;
using Orchard.UI.Admin;
using Orchard.UI.Navigation;
using Orchard.UI.Notify;
using Orchard.Users.Models;
using Skywalker.Webshop.Helpers;
using Skywalker.Webshop.Models;
using Skywalker.Webshop.Services;
using Skywalker.Webshop.ViewModels;

namespace Skywalker.Webshop.Controllers {

    [Admin]
    public class CustomerAdminController : Controller, IUpdateModel {
        private dynamic Shape { get; set; }
        private Localizer T { get; set; }
        private readonly ICustomerService _customerService;
        private readonly ISiteService _siteService;
        private readonly IContentManager _contentManager;
        private readonly INotifier _notifier;
        private readonly IOrderService _orderService;

        public CustomerAdminController
        (
            ICustomerService customerService, 
            IShapeFactory shapeFactory, 
            ISiteService siteService, 
            IContentManager contentManager, 
            INotifier notifier,
            IOrderService orderService
        ) 
        {
            Shape            = shapeFactory;
            T                = NullLocalizer.Instance;
            _customerService = customerService;
            _siteService     = siteService;
            _contentManager  = contentManager;
            _notifier        = notifier;
            _orderService = orderService;
        }

        public ActionResult Index(PagerParameters pagerParameters, CustomersSearchVM search) {

            // Create a basic query that selects all customer content items, joined with the UserPartRecord table
            var customerQuery = _customerService.GetCustomers().Join<UserPartRecord>().List();

            // If the user specified a search expression, update the query with a filter
            if (!string.IsNullOrWhiteSpace(search.Expression)) {
                
                var expression = search.Expression.Trim();

                customerQuery = from customer in customerQuery
                        where
                            customer.FirstName.Contains(expression, StringComparison.InvariantCultureIgnoreCase) ||
                            customer.LastName.Contains(expression, StringComparison.InvariantCultureIgnoreCase) ||
                            customer.As<UserPart>().Email.Contains(expression)
                        select customer;
            }

            // Project the query into a list of customer shapes
            var customersProjection = from customer in customerQuery
                                      select Shape.Customer
                                      (
                                        Id: customer.Id, 
                                        FirstName: customer.FirstName,
                                        LastName: customer.LastName,
                                        Email: customer.As<UserPart>().Email,
                                        CreatedAt: customer.CreatedUtc
                                      );

            // The pager is used to apply paging on the query and to create a PagerShape
            var pager = new Pager(_siteService.GetSiteSettings(), pagerParameters.Page, pagerParameters.PageSize);

            // Apply paging
            var customers = customersProjection.Skip(pager.GetStartIndex()).Take(pager.PageSize);

            // Construct a Pager shape
            var pagerShape = Shape.Pager(pager).TotalItemCount(customerQuery.Count());

            // Create the viewmodel
            var model = new CustomersIndexVM(customers, search, pagerShape);

            return View(model);
        }

        public ActionResult Edit(int id) {
            var customer = _customerService.GetCustomer(id);
            var model = _contentManager.BuildEditor(customer);

            // Casting to avoid invalid (under medium trust) reflection over the protected View method and force a static invocation.
            return View((object)model);
        }

        [HttpPost, ActionName("Edit")]
        public ActionResult EditPOST(int id)
        {
            var customer = _customerService.GetCustomer(id);
            var model = _contentManager.UpdateEditor(customer, this);

            if (!ModelState.IsValid)
                return View(model);

            _notifier.Add(NotifyType.Information, T("Your customer has been saved"));
            return RedirectToAction("Edit", new { id });
        }

        public ActionResult ListAddresses(int id) {
            var addresses = _customerService.GetAddresses(id).ToArray();
            return View(addresses);
        }

        public ActionResult ListOrders(int id)
        {
            var orders = _orderService.GetOrders(id).ToArray();
            return View(orders);
        }

        bool IUpdateModel.TryUpdateModel<TModel>(TModel model, string prefix, string[] includeProperties, string[] excludeProperties) {
            return TryUpdateModel(model, prefix, includeProperties, excludeProperties);
        }

        void IUpdateModel.AddModelError(string key, LocalizedString errorMessage) {
            ModelState.AddModelError(key, errorMessage.Text);
        }
    }
}

Views/CustomerAdmin/Edit.cshtml
@{
    Layout.Title = "Edit Customer";
}

@using(Html.BeginFormAntiForgeryPost())
{
    @Display(Model)
}

Views/CustomerAdmin/Index.cshtml
@model Skywalker.Webshop.ViewModels.CustomersIndexVM
@{
    Script.Require("ShapesBase");
    Layout.Title = T("Customers").ToString();
}

@using(Html.BeginForm("Index", "CustomerAdmin", FormMethod.Get)) {
    <fieldset class="bulk-actions">
        <label for="search">@T("Search:")</label>
        @Html.TextBoxFor(m => m.Search.Expression)
        <button type="submit">@T("Search")</button>
        <a href="@Url.Action("Index")">@T("Clear")</a>
    </fieldset>
}
<fieldset>
    <table class="items" summary="@T("This is a table of the customers in your application")">
        <colgroup>
            <col id="Col1" />
            <col id="Col2" />
            <col id="Col3" />
            <col id="Col4" />
            <col id="Col5" />
            <col id="Col6" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col">&nbsp;&darr;</th>
                <th scope="col">@T("FirstName")</th>
                <th scope="col">@T("LastName")</th>
                <th scope="col">@T("Email")</th>
                <th scope="col">@T("Created")</th>
                <th scope="col">@T("Actions")</th>
            </tr>
        </thead>
        @foreach (var customer in Model.Customers) {
        <tr>
            <td>@customer.Id</td>
            <td>@customer.FirstName</td>
            <td>@customer.LastName</td>
            <td>@customer.Email</td>
            <td>@customer.CreatedAt</td>
            <td>
                <div>
                    <a href="@Url.Action("Edit", new {customer.Id})" title="@T("Edit")">@T("Edit")</a>@T(" | ")
                    <a href="@Url.Action("List", "AddressAdmin", new {customerId = customer.Id})" title="@T("Addresses")">@T("Addresses")</a>@T(" | ")
                    <a href="@Url.Action("Delete", new {customer.Id, returnUrl = Request.Url.PathAndQuery})">@T("Delete")</a>
                </div>
            </td>
        </tr>
        } 
    </table>
    @Display(Model.Pager)
</fieldset>

Views/CustomerAdmin/ListAddresses.cshtml
@model IList<Skywalker.Webshop.Models.AddressPart>
@{
    Layout.Title = T("Addresses");
}

<table class="items" summary="@T("This is a table of the addresses of the current customer in your application")">
    <colgroup>
        <col id="Col1" />
        <col id="Col2" />
        <col id="Col3" />
    </colgroup>
    <thead>
        <tr>
            <th scope="col">&nbsp;&darr;</th>
            <th scope="col">@T("Type")</th>
            <th scope="col">@T("Actions")</th>
        </tr>
    </thead>
    @foreach (var address in Model) {
    <tr>
        <td>@address.Id</td>
        <td>@address.Type</td>
        <td>
            <div>
                <a href="@Url.Action("Edit", "AddressAdmin", new {address.Id})" title="@T("Edit")">@T("Edit")</a>
            </div>
        </td>
    </tr>
    } 
</table>

Views/CustomerAdmin/ListOrders.cshtml
@model IList<Skywalker.Webshop.Models.OrderRecord>
@{
    Layout.Title = T("Orders");
}

<table class="items" summary="@T("This is a table of the orders of the current customer in your application")">
        <colgroup>
            <col id="Col1" />
            <col id="Col2" />
            <col id="Col3" />
            <col id="Col4" />
            <col id="Col5" />
            <col id="Col6" />
            <col id="Col7" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col">&nbsp;&darr;</th>
                <th scope="col">@T("Number")</th>
                <th scope="col">@T("Status")</th>
                <th scope="col">@T("Total")</th>
                <th scope="col">@T("Created")</th>
                <th scope="col">@T("Paid")</th>
                <th scope="col">@T("Actions")</th>
            </tr>
        </thead>
        @foreach (var order in Model) {
        <tr>
            <td>@order.Id</td>
            <td>@order.Number</td>
            <td>@order.Status</td>
            <td>@order.Total</td>
            <td>@order.CreatedAt</td>
            <td>@order.PaidAt</td>
            <td>
                <div>
                    <a href="@Url.Action("Edit", "OrderAdmin", new {order.Id, returnUrl = Request.Url.PathAndQuery})" title="@T("Edit")">@T("Edit")</a>
                </div>
            </td>
        </tr>
        } 
    </table>